version: '0.5'
lastBuildDate: '2023-07-14T05:00:00'
lastUploadDate: '2023-07-14T06:00:00'
slxs:
- fullName: full-test-cluster-cpu
  name: test-cluster-cpu
tombstones:
- fullName: full-test-cluster-disk
  # NB: Setting the lastSeen value to something different than the mocked value
  # to test that the lastSeen value is actually getting updated
  lastSeen: 2023-07-14 05:00:00
# Also including an extra tombstone to make sure it's reserved in the merged manifest
# Note that since we're round-tripping through a data conversion these comments will
# not be preserved in the newly-generated manifest
- fullName: full-test-cluster-mem
  lastSeen: 2023-07-14 05:00:00
