version: '0.5'
lastBuildDate: '2023-07-14T05:00:00'
lastUploadDate: '2023-07-14T06:00:00'
slxs:
- fullName: full-test-cluster-cpu
  name: test-cluster-cpu
tombstones:
- fullName: full-test-cluster-disk
  lastSeen: 2023-07-14 06:00:00
- fullName: full-test-cluster-mem
  lastSeen: 2023-07-14 05:00:00
