apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  icon: AnalysisL3
  statement: Cortex Metrics ingestor ring should be healthy
  asMeasuredBy: Ring health reported by internal metrics scaping with kubectl. 
  owners:
  - {{workspace.owner_email}}
  alias: Cortex Ingester Health
  configProvided:
  - name: SLX_PLACEHOLDER
    value: {{cluster.name}}-platform-placeholder
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}" 