apiVersion: runwhen.com/v1
kind: ServiceLevelIndicator
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  displayUnitsLong: Number
  displayUnitsShort: num
  locations:
    - {{default_location}}
  description: Measures failing reconcilers reported by flux using GMP and promql
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-public-codecollection.git
    ref: main
    pathToRobot: codebundles/gcp-opssuite-promql/sli.robot
  intervalStrategy: intermezzo
  intervalSeconds: 30
  configProvided:
    - name: TRANSFORM
      value: Raw
    - name: DATA_COLUMN
      value: '1'
    - name: NO_RESULT_OVERWRITE
      value: 'Yes'
    - name: PROJECT_ID
      value: {{custom.gcp_project_id}}
    - name: PROMQL_STATEMENT
      value: >-
        sum(gotk_reconcile_condition{namespace=~"flux-system",type="Ready",status="False",kind=~"Kustomization|HelmRelease"})
    - name: NO_RESULT_VALUE
      value: '0'
  secretsProvided:
    - name: ops-suite-sa
      workspaceKey: {{custom.gcp_ops_suite_sa}}
  servicesProvided:
    - name: curl
      locationServiceName: curl-service.shared

