apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  locations:
    - {{default_location}}
  description: Measures ____
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection.git
    ref: main
    pathToRobot: codebundles/gcloud-node-preempt/runbook.robot
  intervalStrategy: intermezzo
  intervalSeconds: 300
  configProvided:
    - name: GCP_PROJECT_ID
      value: {{custom.gcp_project_id}}
  secretsProvided:
    - name: gcp_credentials_json
      workspaceKey: {{custom.gcp_ops_suite_sa}}
  servicesProvided:
    - name: gcloud
      locationServiceName: gcloud-service.shared