apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/google-cloud.svg
  alias: GCP Quota Errors
  asMeasuredBy: Quota Issues reported in Google Managed Prometheus
  configProvided:
  - name: SLX_PLACEHOLDER
    value: gcp-quota
  owners:
  - {{workspace.owner_email}}
  statement: GCP Quota usage should not be approaching 100% for any object.