## Needs tuning as soon as we can match on application resource
apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  location: {{default_location}}
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection
    ref: main
    pathToRobot: codebundles/k8s-argocd-application-health/runbook.robot
  configProvided:
    - name: binary_name
      value: {{custom.kubernetes_distribution_binary}}
    - name: APPLICATION
      value: {{match_resource.resource.metadata.name}}
    - name: APPLICATION_TARGET_NAMESPACE
      value:  {{match_resource.resource.spec.destination.namespace}}
    - name: APPLICATION_APP_NAMESPACE
      value: {{match_resource.resource.metadata.namespace}}
    - name: ERROR_PATTERN
      value: 'Error|Exception'
    - name: CONTEXT
      value: {{context}}
  secretsProvided:
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
  servicesProvided:
    - name: {{custom.kubernetes_distribution_binary}}
      locationServiceName: {{custom.kubernetes_distribution_binary}}-service.shared