apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/vault-1.svg
  alias: {{match_resource.resource.metadata.name}} - Vault Health
  asMeasuredBy: >-
    The http response code on the /sys/health api endpoint. Docs:
    https://developer.hashicorp.com/vault/api-docs/system/health
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: The Vault instances should be unsealed and API services responsive
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}" 
