apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  location: {{default_location}}
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection
    ref: main
    pathToRobot: codebundles/k8s-fluxcd-kustomization-health/runbook.robot
  configProvided:
    - name: DISTRIBUTION
      value: {{custom.kubernetes_distribution}}
    - name: NAMESPACE
      value: '{{match_resource.resource.metadata.namespace}}'
    - name: RESOURCE_NAME
      value: '{{match_resource.resource.kind}}.{{match_resource.resource.apiVersion.split('/')[0]}}'
    - name: CONTEXT
      value: {{context}}
    - name: KUBERNETES_DISTRIBUTION_BINARY
      value: {{custom.kubernetes_distribution_binary}}
  secretsProvided:
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
  servicesProvided:
    - name: {{custom.kubernetes_distribution_binary}}
      locationServiceName: {{custom.kubernetes_distribution_binary}}-service.shared