apiVersion: runwhen.com/v1
kind: ServiceLevelIndicator
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  displayUnitsLong: Number
  displayUnitsShort: '#'
  locations:
    - {{default_location}}
  description: Measures ____
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-public-codecollection.git
    ref: main
    pathToRobot: codebundles/k8s-kubectl-get/sli.robot
  intervalStrategy: intermezzo
  intervalSeconds: 30
  configProvided:
    - name: DISTRIBUTION
      value: Kubernetes
    - name: KUBECTL_COMMAND
      value: kubectl get certificates --all-namespaces
    - name: CALCULATION
      value: Count
    - name: CALCULATION_FIELD
      value: ''
    - name: SEARCH_FILTER
      value: status.conditions[?type==`Ready` && status!=`True`]
  secretsProvided:
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
  servicesProvided:
    - name: kubectl
      locationServiceName: kubectl-service.shared