apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/Jenkins_logo.svg
  alias: {{match_resource.resource.metadata.name}} Health
  asMeasuredBy: The Running state of desired pods and the health endpoints. Commands might require environment variables or secrets to be set for valid authentication. 
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: Jenkins endpoints should be responsive and healthy state. 
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}"   