apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec: 
  location: {{default_location}}
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection
    ref: main
    pathToRobot: codebundles/k8s-deployment-healthcheck/runbook.robot
  configProvided:
    - name: DISTRIBUTION
      value: {{custom.kubernetes_distribution}}
    - name: NAMESPACE
      value: {{match_resource.resource.metadata.namespace}}
    - name: CONTEXT
      value: {{context}}
    - name: KUBERNETES_DISTRIBUTION_BINARY
      value: {{custom.kubernetes_distribution_binary}}
    - name: DEPLOYMENT_NAME
      value: {{match_resource.resource.metadata.name}}
    - name: EXPECTED_AVAILABILITY
      value: "1"
    - name: ANOMALY_THRESHOLD
      value: "3"
    - name: LOGS_ERROR_PATTERN
      value: "500"
    - name: LOGS_EXCLUDE_PATTERN
      value: ""
  secretsProvided:
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
  servicesProvided:
    - name: {{custom.kubernetes_distribution_binary}}
      locationServiceName: {{custom.kubernetes_distribution_binary}}-service.shared