apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/flux-icon-color.svg
  alias: {{namespace.name}} Kustomization Health
  asMeasuredBy: The sync/ready status of the Kustomization object.   
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: Kustomizations for {{namespace.name}} should be synced and ready. 
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}" 