apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec: 
  location: {{default_location}}
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection
    ref: main
    pathToRobot: codebundles/k8s-jenkins-healthcheck/runbook.robot
  configProvided:
    - name: KUBERNETES_DISTRIBUTION_BINARY
      value: {{custom.kubernetes_distribution_binary}}
    - name: NAMESPACE
      value: {{match_resource.resource.metadata.namespace}}
    - name: STATEFULSET_NAME
      value: {{match_resource.resource.metadata.name}}
    - name: CONTEXT
      value: {{context}}
  secretsProvided:
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
    - name: JENKINS_SA_USERNAME
{% if custom.jenkins_sa_username_secret_name is defined %}
      workspaceKey: {{custom.jenkins_sa_username_secret_name}}
{% else %}
      value: secret_key_not_specified
{% endif %}
    - name: JENKINS_SA_TOKEN
{% if custom.jenkins_sa_token_secret_name is defined %}
      workspaceKey: {{custom.jenkins_sa_token_secret_name}}
{% else %}
      value: secret_key_not_specified
{% endif %}
  servicesProvided:
    - name: {{custom.kubernetes_distribution_binary}}
      locationServiceName: {{custom.kubernetes_distribution_binary}}-service.shared