apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/kubernetes/resources/labeled/ns.svg
  alias: {{namespace.name}} Namespace Health
  asMeasuredBy: Aggregate score based on Kubernetes API Server queries
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: Overall health for {{namespace.name}} should be 1, 99% of the time. 
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}" 