apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec: 
  location: {{default_location}}
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection
    ref: main
    pathToRobot: codebundles/k8s-vault-healthcheck/runbook.robot
  configProvided:
    - name: KUBERNETES_DISTRIBUTION_BINARY
      value: {{custom.kubernetes_distribution_binary}}
    - name: NAMESPACE
      value: {{match_resource.resource.metadata.namespace}}
    - name: STATEFULSET_NAME
      value: {{match_resource.resource.metadata.name}}
    - name: CONTEXT
      value: {{context}}
    - name: VAULT_URL
{% for container in match_resource.resource.spec.template.spec.containers %}
  {% if container.name == "vault" %}
    {% for env in container.env %}
      {% if env.name == "VAULT_ADDR" %}
      value: {{env.value}}
      {% endif %}
    {% endfor %}
  {% endif %}
{% endfor %}
    - name: LABELS
      value: {{match_resource.resource.metadata.labels["app.kubernetes.io/name"]}}
  secretsProvided:
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
  servicesProvided:
    - name: {{custom.kubernetes_distribution_binary}}
      locationServiceName: {{custom.kubernetes_distribution_binary}}-service.shared