apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/kubernetes/resources/labeled/ds.svg
  alias: {{match_resource.resource.metadata.name}} DaemonSet Health
  asMeasuredBy: The Running state of desired pods.    
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: Statefulset {{match_resource.resource.metadata.name}} should be in a healthy state. 
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}"  