apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/kong-logomark-color.svg
  alias: {{match_resource.resource.metadata.name}}-Kong Ingress HTTP Errors
  asMeasuredBy: The combined score of http error rate, upstream errors, and request latency as reported by Google Managed Prometheus (GMP). 
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: Kong Ingress objects should available and performant 99.5% of the time.  
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}" 