apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/nginx-1.svg
  alias: {{match_resource.resource.metadata.name}} Nginx Ingress HTTP Errors
  asMeasuredBy: Rate of HTTP status codes that are not "200|201|301|308" reported by the prometheus nginx exporter and Google Managed Prometheus (GMP). 
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: {{match_resource.resource.metadata.name}} Nginx Ingress should have a count of http errors that is minimal or none. 
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}" 