apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec: 
  location: {{default_location}}
  codeBundle:
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection
    ref: main
    pathToRobot: codebundles/curl-gmp-nginx-ingress-inspection/runbook.robot
  configProvided:
    - name: KUBERNETES_DISTRIBUTION_BINARY
      value: {{custom.kubernetes_distribution_binary}}
    - name: NAMESPACE
      value: {{match_resource.resource.metadata.namespace}}
    - name: CONTEXT
      value: {{context}}
    - name: TIME_SLICE
      value: '10m'
    - name: GCP_PROJECT_ID
      value: {{custom.gcp_project_id}}
    - name: ERROR_CODES
      value: '500|501|502'
    - name: INGRESS_HOST
      value: {{match_resource.resource.spec.rules[0].host}}
    - name: INGRESS_SERVICE 
      value: {{match_resource.resource.spec.rules[0].http.paths[0].backend.service.name}}
    - name: INGRESS_OBJECT_NAME
      value: {{match_resource.resource.metadata.name}}
  secretsProvided:
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
    - name: gcp_credentials_json
      workspaceKey: {{custom.gcp_ops_suite_sa}}
  servicesProvided:
    - name: {{custom.kubernetes_distribution_binary}}
      locationServiceName: {{custom.kubernetes_distribution_binary}}-service.shared
    - name: gcloud
      locationServiceName: gcloud-service.shared