apiVersion: apps/v1
kind: Deployment
metadata:
  name: runwhen-local
  labels:
    app: runwhen-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runwhen-local
  template:
    metadata:
      labels:
        app: runwhen-local
    spec:
      containers:
      - name: runwhen-local
        image: ghcr.io/runwhen-contrib/runwhen-local:latest
        imagePullPolicy: Always
        ports:
          - name: mkdocs
            containerPort: 8081
            protocol: TCP
          - name: django
            containerPort: 8000
            protocol: TCP
        env: 
        - name: AUTORUN_WORKSPACE_BUILDER_INTERVAL
          value: "1800"
        - name: RW_LOCAL_TERMINAL_DISABLED
          value: "true"
        volumeMounts:
        - name: shared-volume
          mountPath: "/shared"
        - name: secret-volume
          mountPath: "/shared/kubeconfig"
          subPath: "kubeconfig"
        - name: configmap-volume
          mountPath: "/shared/workspaceInfo.yaml"
          subPath: "workspaceInfo.yaml"
        livenessProbe:
          httpGet:
            path: /
            port: mkdocs
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 20
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1"
      volumes:
      - name: shared-volume
        emptyDir: {}
      - name: secret-volume
        secret:
          secretName: runwhen-local-kubeconfig
          items:
            - key: kubeconfig
              path: kubeconfig
      - name: configmap-volume
        configMap:
          name: runwhen-local-workspaceinfo
          items:
            - key: workspaceInfo.yaml
              path: workspaceInfo.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: runwhen-local
spec:
  selector:
    app: runwhen-local
  ports:
    - name: mkdocs
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: django
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: neo4j
      protocol: TCP
      port: 7687
      targetPort: 7687
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: runwhen-local-workspaceinfo
data:
  workspaceInfo.yaml: |
    workspaceName: my-workspace
    # All content with [placeholder] is only updated
    # and auto-generated when using the RunWhen Platform
    # leave it as [placeholder] if only using RunWhen Local
    # See https://docs.runwhen.com/public/runwhen-local/advanced-configuration 
    # or https://docs.runwhen.com/public/runwhen-local/features/workspace-builder
    token: placeholder
    workspaceOwnerEmail: tester@my-company.com
    papiURL: placeholder
    defaultLocation: placeholder
    defaultLOD: 2
    namespaceLODs:
      kube-system: 0
      kube-public: 0
      kube-node-lease: 0
    custom:
      kubernetes_distribution: Kubernetes
      kubernetes_distribution_binary: kubectl
      
      # Possible values are gcp, aws, none
      cloud_provider: gcp
      
      # Possible values are gmp, promql, none
      prometheus_provider: gmp

      # If using GCP and wanting to use GCP integrations  
      gcp_project_id: placeholder 
      
      # Secret names are used when integrating the RunWhen Platform
      # with your environment. RunWhen has no access to this data, 
      # as the secret name and content comes from your own configuration. 
      kubeconfig_secret_name: kubeconfig
      gcp_ops_suite_sa: ops-suite-sa
