apiVersion: v1
kind: Service
metadata:
  name: runwhen-local
spec:
  selector:
    app: runwhen-local
  ports:
    - name: mkdocs
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: django
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: neo4j
      protocol: TCP
      port: 7687
      targetPort: 7687