apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
  - resourceTypes:
    - namespace
    matchRules:
    - type: pattern
      pattern: "flux-system"
      properties: [name]
      mode: substring
    slxs:
    - baseName: flux-reconcile
      levelOfDetail: detailed
      baseTemplateName: flux-reconciler-gcp-promql
      outputItems:
        - type: slx
        - type: sli
