apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - cluster
      matchRules:
        - type: and
          matches:
            - resourceType: variables
              type: pattern
              pattern: "gcp"
              properties: [custom/cloud_provider]
              mode: substring
            ## TODO
            ## See if we can match on cloud.google.com/gke-preemptible=true labels on nodes
            - resourceType: variables
              type: pattern
              pattern: "true"
              properties: [custom/gcp_preempt_nodes]
              mode: exact
      slxs:
        - baseName: node-preempt
          qualifiers: [resource]
          baseTemplateName: gcloud-node-preempt
          levelOfDetail: detailed
          outputItems:
            - type: slx
            - type: sli
            - type: slo
            - type: runbook
              templateName: gcloud-node-preempt-taskset.yaml
