apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
  - resourceTypes:
    - ingress
    matchRules:
    - type: and
      matches:
      - type: pattern
        pattern: ".+"
        properties: [name]
        mode: substring
    - type: not
      predicate: 
        type: exists
        path: spec/tls/hosts
    slxs:
    - baseName: http-ok
      qualifiers: [resource]
      baseTemplateName: http-ok
      levelOfDetail: basic
      outputItems:
        - type: slx
        - type: sli
        - type: slo
        - type: runbook
          templateName: http-ok-taskset.yaml
