apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
  - resourceTypes:
    - ingress
    matchRules:
    - type: and
      matches:
      - type: pattern
        pattern: ".+"
        properties: [name]
        mode: substring
      - type: pattern
        pattern: ".+"
        properties: [spec/tls/hosts]
        mode: substring
    slxs:
    - baseName: http-ok-tls
      qualifiers: [resource]
      baseTemplateName: http-ok-tls
      levelOfDetail: basic
      outputItems:
        - type: slx
        - type: sli
        - type: slo
        - type: runbook
          templateName: http-ok-tls-taskset.yaml
