apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - certificates.cert-manager.io
        - certificaterequests.cert-manager.io
      matchRules:
        - type: and
          matches:
            - type: pattern
              pattern: ".+"
              properties: [name]
              mode: substring
      slxs:
        - baseName: cert-health
          qualifiers: [resource]
          baseTemplateName: k8s-certmanager-certificate-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: k8s-certmanager-certificate-health-taskset.yaml
