apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - namespace
      matchRules:
        - type: and
          matches:
            - type: pattern
              pattern: ".+"
              properties: [name]
              mode: substring
      slxs:
        - baseName: sa-check
          qualifiers: [namespace]
          baseTemplateName: k8s-serviceaccount-check
          levelOfDetail: detailed
          outputItems:
            - type: slx
            - type: runbook
              templateName: k8s-serviceaccount-check-taskset.yaml
