apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - namespace
      matchRules:
        - type: pattern
          pattern: "."
          properties: [name]
          mode: substring
      slxs:
        - baseName: image-check
          levelOfDetail: detailed
          qualifiers: [namespace]
          baseTemplateName: k8s-image-check
          outputItems:
            - type: slx
            - type: runbook
              templateName: k8s-image-check-taskset.yaml
