apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - ingress
      matchRules:
        - type: and
          matches:
            - type: pattern
              pattern: ".+"
              properties: [name]
              mode: substring
      slxs:
        - baseName: ingress-health
          qualifiers: [resource]
          baseTemplateName: k8s-ingress-healthcheck
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: runbook
              templateName: k8s-ingress-healthcheck-taskset.yaml
