apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - helmreleases.helm.toolkit.fluxcd.io
      matchRules:
        - type: and
          matches:
            - type: pattern
              pattern: ".+"
              properties: [name]
              mode: substring
      slxs:
        - baseName: flux-helm
          qualifiers: [resource]
          baseTemplateName: k8s-flux-helm-health
          levelOfDetail: detailed
          outputItems:
            - type: slx
            - type: runbook
              templateName: k8s-flux-helm-health-taskset.yaml
