apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - deployment
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: depl-health
          levelOfDetail: detailed
          qualifiers: [resource]
          baseTemplateName: k8s-deployment-health
          outputItems:
            - type: slx
            # - type: sli
            - type: runbook
              templateName: k8s-deployment-health-taskset.yaml
