apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - stateful_set
      matchRules:
        - type: pattern
          pattern: "artifactory"
          properties: [name]
          mode: substring
      slxs:
        - baseName: arti-health
          levelOfDetail: basic
          qualifiers: [namespace]
          baseTemplateName: k8s-artifactory-healthcheck
          outputItems:
            - type: slx
            - type: runbook
              templateName: k8s-artifactory-healthcheck-taskset.yaml
