apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
  - resourceTypes:
    - namespace
    matchRules:
    - type: pattern
      pattern: "."
      properties: [name]
      mode: substring
    slxs:
    - baseName: pod-resources
      levelOfDetail: detailed
      qualifiers: [namespace]
      baseTemplateName: k8s-pod-resources
      outputItems:
        - type: slx
        - type: runbook
          templateName: k8s-pod-resources-taskset.yaml