apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
    - resourceTypes:
        - ingress
      matchRules:
        - type: and
          matches:
            - type: pattern
              pattern: "."
              properties: [name]
              mode: substring
            - type: pattern
              pattern: "nginx"
              properties: [spec/ingressClassName]
              mode: substring
            - resourceType: variables
              type: pattern
              pattern: "gcp"
              properties: [custom/cloud_provider]
              mode: substring
      slxs:
        - baseName: ngx-ing-gmp
          qualifiers: [resource]
          baseTemplateName: nginx-ingress-http-errors-gcp-promql
          levelOfDetail: detailed
          outputItems:
            - type: slx
            - type: sli
            - type: slo
            - type: runbook
              templateName: nginx-ingress-http-errors-gcp-promql-taskset.yaml