"""
Loader for the AWS resource-type registry.

The registry maps every CloudQuery AWS table name to its AWS Cloud Control API
resource type -- the CloudFormation resource type name -- plus metadata used by
the native ``awsapi`` indexer:

* canonical name = the CloudQuery table name (e.g. ``aws_ec2_instances``)
* CFN type for Cloud Control / generic discovery (e.g. ``AWS::EC2::Instance``)
* aliases for backward compatibility with legacy RWL ``resource_type_name``
  values (e.g. ``account`` -> ``aws_iam_accounts``, ``ec2_instance`` ->
  ``aws_ec2_instances``)
* ``typed_collector`` flag indicating whether ``awsapi_resource_types`` ships a
  hand-written boto3 collector for this table
* ``mandatory`` flag indicating whether the indexer must always emit the type
  (today only ``aws_iam_accounts``, the account anchor everything is scoped
  under)

The data lives in ``aws_resource_type_registry.yaml`` next to this module. That
YAML is generated by ``scripts/aws/sync_aws_resource_type_registry.py``;
hand-edits to the YAML get overwritten on the next sync. To change behavior for
a specific table, edit ``scripts/aws/aws_resource_type_overrides.yaml`` and
re-run the sync script.

This module is intentionally read-only: it loads, caches, and exposes the
registry. It does not own collector callables or generation-rule semantics.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Mapping, Optional

import yaml

_DEFAULT_REGISTRY_PATH = Path(__file__).with_name("aws_resource_type_registry.yaml")


@dataclass(frozen=True)
class AwsResourceTypeEntry:
    """One row of the registry.

    ``cloudquery_table_name`` is the canonical key. Lookups by alias resolve to
    the same entry (no duplicates). ``cfn_type`` may be ``None`` for tables that
    have no Cloud Control resource type (reports, metrics, cost rollups, the
    synthesized account anchor...); such tables are skipped by generic
    discovery.
    """

    cloudquery_table_name: str
    cfn_type: Optional[str]
    cfn_type_source: Optional[str]
    category: Optional[str]
    aliases: tuple[str, ...]
    typed_collector: bool
    mandatory: bool
    # The full, EXPLICIT set of names that should match this resource type:
    # the canonical CloudQuery table name plus every legacy/alias name
    # generation rules have historically used (e.g. ``account`` /
    # ``aws_account`` for ``aws_iam_accounts``). This is the accepted-name set
    # the alias-aware matcher and selective discovery use; it is generated by
    # the sync script (canonical + aliases + any extra ``match_names``
    # overrides) so matching never depends on positional alias ordering.
    # Always non-empty and always includes the canonical name first.
    match_names: tuple[str, ...] = ()

    def known_names(self) -> tuple[str, ...]:
        """Every name (canonical + aliases/legacy) that resolves to this entry.

        Returns the explicit ``match_names`` accepted-name set when present;
        otherwise falls back to ``canonical + aliases`` for backward
        compatibility with older registry YAML.
        """
        if self.match_names:
            return self.match_names
        return (self.cloudquery_table_name, *self.aliases)


@dataclass(frozen=True)
class AwsRegistryMetadata:
    source: Optional[str] = None
    snapshot_date: Optional[str] = None
    total_tables: int = 0
    typed_collectors: int = 0
    cfn_types_assigned: int = 0
    generator: Optional[str] = None
    notes: Optional[str] = None


@dataclass
class AwsResourceTypeRegistry:
    metadata: AwsRegistryMetadata
    entries: tuple[AwsResourceTypeEntry, ...]
    _by_canonical: dict[str, AwsResourceTypeEntry] = field(default_factory=dict, repr=False)
    _by_alias: dict[str, AwsResourceTypeEntry] = field(default_factory=dict, repr=False)
    _by_match_name: dict[str, AwsResourceTypeEntry] = field(default_factory=dict, repr=False)
    _by_cfn_type_lower: dict[str, AwsResourceTypeEntry] = field(default_factory=dict, repr=False)

    def __post_init__(self) -> None:
        for entry in self.entries:
            self._by_canonical[entry.cloudquery_table_name] = entry
            for alias in entry.aliases:
                if not alias:
                    continue
                # Aliases must not collide with another canonical name or alias;
                # the sync script enforces this, but verify defensively in case
                # someone hand-edits the YAML.
                if alias in self._by_canonical and self._by_canonical[alias] is not entry:
                    raise ValueError(
                        f"Alias {alias!r} collides with canonical table name "
                        f"belonging to a different entry"
                    )
                if alias in self._by_alias and self._by_alias[alias] is not entry:
                    raise ValueError(
                        f"Alias {alias!r} is registered for both "
                        f"{self._by_alias[alias].cloudquery_table_name!r} and "
                        f"{entry.cloudquery_table_name!r}"
                    )
                self._by_alias[alias] = entry
            # Index the explicit accepted-name set and enforce the disjointness
            # invariant: the union of match_names across all registry entries
            # must be unique, so a requested name can never resolve to two
            # different resource types (which would silently mis-route SLXs).
            for match_name in entry.known_names():
                if not match_name:
                    continue
                existing = self._by_match_name.get(match_name)
                if existing is not None and existing is not entry:
                    raise ValueError(
                        f"Accepted name {match_name!r} is registered for both "
                        f"{existing.cloudquery_table_name!r} and "
                        f"{entry.cloudquery_table_name!r}; accepted-name sets "
                        f"(match_names) must be pairwise disjoint."
                    )
                self._by_match_name[match_name] = entry
            if entry.cfn_type:
                # CFN types are case-sensitive on the wire but we index
                # lower-cased for robust matching. Multiple registry entries can
                # occasionally share a CFN type; the first one wins, which is
                # deterministic because entries arrive sorted by canonical name.
                key = entry.cfn_type.lower()
                self._by_cfn_type_lower.setdefault(key, entry)

    def find(self, name: str) -> Optional[AwsResourceTypeEntry]:
        """Return the entry for any accepted name (canonical CQ table name,
        alias, or legacy ``match_names`` entry), else None.

        Looking up via the explicit accepted-name index makes resolution
        independent of positional alias ordering.
        """
        if not name:
            return None
        entry = self._by_canonical.get(name)
        if entry is not None:
            return entry
        entry = self._by_match_name.get(name)
        if entry is not None:
            return entry
        return self._by_alias.get(name)

    def find_by_cfn_type(self, cfn_type: Optional[str]) -> Optional[AwsResourceTypeEntry]:
        """Look up the registry entry whose ``cfn_type`` matches this string.

        Used by the Cloud Control generic-discovery pass to route each
        ``TypeName`` value (e.g. ``AWS::S3::Bucket``) back to the registry entry
        whose ``cloudquery_table_name`` is the canonical RWL identifier for that
        type.
        """
        if not cfn_type:
            return None
        return self._by_cfn_type_lower.get(cfn_type.lower())

    def __contains__(self, name: object) -> bool:
        return isinstance(name, str) and self.find(name) is not None

    def __iter__(self) -> Iterable[AwsResourceTypeEntry]:
        return iter(self.entries)

    def __len__(self) -> int:
        return len(self.entries)

    def all_canonical_names(self) -> tuple[str, ...]:
        return tuple(entry.cloudquery_table_name for entry in self.entries)

    def all_match_names(self) -> tuple[str, ...]:
        """Every accepted name across all entries (canonical + legacy/aliases).

        Guaranteed pairwise disjoint by the load-time invariant in
        ``__post_init__``.
        """
        names: list[str] = []
        for entry in self.entries:
            names.extend(entry.known_names())
        return tuple(names)

    def all_cfn_types(self) -> tuple[str, ...]:
        return tuple(
            entry.cfn_type for entry in self.entries if entry.cfn_type
        )

    def typed_collector_tables(self) -> tuple[str, ...]:
        return tuple(
            entry.cloudquery_table_name
            for entry in self.entries
            if entry.typed_collector
        )

    def mandatory_tables(self) -> tuple[str, ...]:
        return tuple(
            entry.cloudquery_table_name
            for entry in self.entries
            if entry.mandatory
        )


def _coerce_aliases(value: object) -> tuple[str, ...]:
    if not value:
        return ()
    if isinstance(value, (list, tuple)):
        return tuple(str(v) for v in value if v)
    return (str(value),)


def _compute_match_names(
    table_name: str,
    aliases: tuple[str, ...],
    raw_match_names: object,
) -> tuple[str, ...]:
    """Build the accepted-name set for an entry.

    Always includes the canonical CloudQuery table name first, followed by
    every alias and any explicit ``match_names`` from the YAML (deduplicated,
    order-preserving). When the YAML predates the ``match_names`` field the
    result is just ``canonical + aliases``, preserving old behavior.
    """
    names: list[str] = [table_name]
    for candidate in (*aliases, *_coerce_aliases(raw_match_names)):
        if candidate and candidate not in names:
            names.append(candidate)
    return tuple(names)


def _build_metadata(payload: Mapping[str, object]) -> AwsRegistryMetadata:
    return AwsRegistryMetadata(
        source=_optional_str(payload.get("source")),
        snapshot_date=_optional_str(payload.get("snapshot_date")),
        total_tables=int(payload.get("total_tables") or 0),
        typed_collectors=int(payload.get("typed_collectors") or 0),
        cfn_types_assigned=int(payload.get("cfn_types_assigned") or 0),
        generator=_optional_str(payload.get("generator")),
        notes=_optional_str(payload.get("notes")),
    )


def _optional_str(value: object) -> Optional[str]:
    if value is None:
        return None
    s = str(value).strip()
    return s or None


def _build_entries(types_payload: Mapping[str, Mapping[str, object]]) -> tuple[AwsResourceTypeEntry, ...]:
    entries: list[AwsResourceTypeEntry] = []
    for table_name, body in sorted(types_payload.items()):
        if not isinstance(body, Mapping):
            raise ValueError(f"Registry entry {table_name!r} is not a mapping")
        aliases = _coerce_aliases(body.get("aliases"))
        entries.append(
            AwsResourceTypeEntry(
                cloudquery_table_name=str(table_name),
                cfn_type=_optional_str(body.get("cfn_type")),
                cfn_type_source=_optional_str(body.get("cfn_type_source")),
                category=_optional_str(body.get("category")),
                aliases=aliases,
                typed_collector=bool(body.get("typed_collector")),
                mandatory=bool(body.get("mandatory")),
                match_names=_compute_match_names(
                    str(table_name), aliases, body.get("match_names")
                ),
            )
        )
    return tuple(entries)


def load_registry_from_path(path: Path) -> AwsResourceTypeRegistry:
    """Load a registry from an explicit YAML path. Bypasses the cache."""
    if not path.exists():
        raise FileNotFoundError(f"AWS resource-type registry not found at {path}")
    with path.open("r", encoding="utf-8") as fh:
        payload = yaml.safe_load(fh) or {}
    if not isinstance(payload, Mapping):
        raise ValueError(f"Registry YAML at {path} did not parse to a mapping")

    metadata = _build_metadata(payload.get("metadata") or {})
    types_payload = payload.get("types") or {}
    if not isinstance(types_payload, Mapping):
        raise ValueError(f"Registry YAML at {path} has non-mapping 'types' section")

    entries = _build_entries(types_payload)
    return AwsResourceTypeRegistry(metadata=metadata, entries=entries)


@lru_cache(maxsize=1)
def load_registry() -> AwsResourceTypeRegistry:
    """Load and cache the registry from the default location."""
    return load_registry_from_path(_DEFAULT_REGISTRY_PATH)


def find_entry(name: str) -> Optional[AwsResourceTypeEntry]:
    """Convenience wrapper around the cached registry's ``find()``."""
    return load_registry().find(name)


def reset_cache() -> None:
    """Clear the cached registry. Intended for tests."""
    load_registry.cache_clear()
