"""
Loader for the Azure resource-type registry.

The registry maps every CloudQuery Azure table name to its ARM resource type
plus metadata used by the native ``azureapi`` indexer:

* canonical name = the CloudQuery table name (e.g. ``azure_compute_virtual_machines``)
* ARM resource type for Resource Graph / generic discovery
* aliases for backward compatibility with legacy RWL ``resource_type_name``
  values (e.g. ``virtual_machine`` -> ``azure_compute_virtual_machines``,
  ``azure_keyvault_vaults`` -> ``azure_keyvault_keyvaults``)
* ``typed_collector`` flag indicating whether ``azureapi_resource_types``
  ships a hand-written ``azure-mgmt-*`` collector for this table
* ``mandatory`` flag indicating whether the indexer must always list the
  type (today only ``azure_resources_resource_groups``)

The data lives in ``azure_resource_type_registry.yaml`` next to this module.
That YAML is generated by ``scripts/azure/sync_azure_resource_type_registry.py``;
hand-edits to the YAML get overwritten on the next sync. To change behavior
for a specific table, edit ``scripts/azure/azure_resource_type_overrides.yaml``
and re-run the sync script.

This module is intentionally read-only: it loads, caches, and exposes the
registry. It does not own collector callables or generation-rule semantics.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Mapping, Optional

import yaml

_DEFAULT_REGISTRY_PATH = Path(__file__).with_name("azure_resource_type_registry.yaml")


@dataclass(frozen=True)
class AzureResourceTypeEntry:
    """One row of the registry.

    ``cloudquery_table_name`` is the canonical key. Lookups by alias resolve
    to the same entry (no duplicates).
    """

    cloudquery_table_name: str
    arm_type: Optional[str]
    arm_type_source: Optional[str]
    category: Optional[str]
    aliases: tuple[str, ...]
    typed_collector: bool
    mandatory: bool

    def known_names(self) -> tuple[str, ...]:
        """Every name (canonical + aliases) that resolves to this entry."""
        return (self.cloudquery_table_name, *self.aliases)


@dataclass(frozen=True)
class AzureRegistryMetadata:
    source: Optional[str] = None
    snapshot_date: Optional[str] = None
    total_tables: int = 0
    typed_collectors: int = 0
    arm_types_assigned: int = 0
    generator: Optional[str] = None
    notes: Optional[str] = None


@dataclass
class AzureResourceTypeRegistry:
    metadata: AzureRegistryMetadata
    entries: tuple[AzureResourceTypeEntry, ...]
    _by_canonical: dict[str, AzureResourceTypeEntry] = field(default_factory=dict, repr=False)
    _by_alias: dict[str, AzureResourceTypeEntry] = field(default_factory=dict, repr=False)
    _by_arm_type_lower: dict[str, AzureResourceTypeEntry] = field(default_factory=dict, repr=False)

    def __post_init__(self) -> None:
        for entry in self.entries:
            self._by_canonical[entry.cloudquery_table_name] = entry
            for alias in entry.aliases:
                if not alias:
                    continue
                # Aliases must not collide with another canonical name or alias;
                # the sync script enforces this, but verify defensively in case
                # someone hand-edits the YAML.
                if alias in self._by_canonical and self._by_canonical[alias] is not entry:
                    raise ValueError(
                        f"Alias {alias!r} collides with canonical table name "
                        f"belonging to a different entry"
                    )
                if alias in self._by_alias and self._by_alias[alias] is not entry:
                    raise ValueError(
                        f"Alias {alias!r} is registered for both "
                        f"{self._by_alias[alias].cloudquery_table_name!r} and "
                        f"{entry.cloudquery_table_name!r}"
                    )
                self._by_alias[alias] = entry
            if entry.arm_type:
                # ARM types are case-insensitive on the wire; we lower-case for
                # lookup. Multiple registry entries occasionally share an ARM
                # type (e.g. legacy duplicates); the first one wins, which is
                # deterministic because entries arrive sorted by canonical name.
                key = entry.arm_type.lower()
                self._by_arm_type_lower.setdefault(key, entry)

    def find(self, name: str) -> Optional[AzureResourceTypeEntry]:
        """Return the entry for a canonical table name or alias, else None."""
        if not name:
            return None
        entry = self._by_canonical.get(name)
        if entry is not None:
            return entry
        return self._by_alias.get(name)

    def find_by_arm_type(self, arm_type: Optional[str]) -> Optional[AzureResourceTypeEntry]:
        """Look up the registry entry whose ``arm_type`` matches this string.

        Used by the generic-resources discovery pass to route each
        ``GenericResource.type`` value (e.g. ``Microsoft.Storage/storageAccounts``)
        back to the registry entry whose ``cloudquery_table_name`` is the
        canonical RWL identifier for that type.
        """
        if not arm_type:
            return None
        return self._by_arm_type_lower.get(arm_type.lower())

    def __contains__(self, name: object) -> bool:
        return isinstance(name, str) and self.find(name) is not None

    def __iter__(self) -> Iterable[AzureResourceTypeEntry]:
        return iter(self.entries)

    def __len__(self) -> int:
        return len(self.entries)

    def all_canonical_names(self) -> tuple[str, ...]:
        return tuple(entry.cloudquery_table_name for entry in self.entries)

    def all_arm_types(self) -> tuple[str, ...]:
        return tuple(
            entry.arm_type for entry in self.entries if entry.arm_type
        )

    def typed_collector_tables(self) -> tuple[str, ...]:
        return tuple(
            entry.cloudquery_table_name
            for entry in self.entries
            if entry.typed_collector
        )

    def mandatory_tables(self) -> tuple[str, ...]:
        return tuple(
            entry.cloudquery_table_name
            for entry in self.entries
            if entry.mandatory
        )


def _coerce_aliases(value: object) -> tuple[str, ...]:
    if not value:
        return ()
    if isinstance(value, (list, tuple)):
        return tuple(str(v) for v in value if v)
    return (str(value),)


def _build_metadata(payload: Mapping[str, object]) -> AzureRegistryMetadata:
    return AzureRegistryMetadata(
        source=_optional_str(payload.get("source")),
        snapshot_date=_optional_str(payload.get("snapshot_date")),
        total_tables=int(payload.get("total_tables") or 0),
        typed_collectors=int(payload.get("typed_collectors") or 0),
        arm_types_assigned=int(payload.get("arm_types_assigned") or 0),
        generator=_optional_str(payload.get("generator")),
        notes=_optional_str(payload.get("notes")),
    )


def _optional_str(value: object) -> Optional[str]:
    if value is None:
        return None
    s = str(value).strip()
    return s or None


def _build_entries(types_payload: Mapping[str, Mapping[str, object]]) -> tuple[AzureResourceTypeEntry, ...]:
    entries: list[AzureResourceTypeEntry] = []
    for table_name, body in sorted(types_payload.items()):
        if not isinstance(body, Mapping):
            raise ValueError(f"Registry entry {table_name!r} is not a mapping")
        entries.append(
            AzureResourceTypeEntry(
                cloudquery_table_name=str(table_name),
                arm_type=_optional_str(body.get("arm_type")),
                arm_type_source=_optional_str(body.get("arm_type_source")),
                category=_optional_str(body.get("category")),
                aliases=_coerce_aliases(body.get("aliases")),
                typed_collector=bool(body.get("typed_collector")),
                mandatory=bool(body.get("mandatory")),
            )
        )
    return tuple(entries)


def load_registry_from_path(path: Path) -> AzureResourceTypeRegistry:
    """Load a registry from an explicit YAML path. Bypasses the cache."""
    if not path.exists():
        raise FileNotFoundError(f"Azure resource-type registry not found at {path}")
    with path.open("r", encoding="utf-8") as fh:
        payload = yaml.safe_load(fh) or {}
    if not isinstance(payload, Mapping):
        raise ValueError(f"Registry YAML at {path} did not parse to a mapping")

    metadata = _build_metadata(payload.get("metadata") or {})
    types_payload = payload.get("types") or {}
    if not isinstance(types_payload, Mapping):
        raise ValueError(f"Registry YAML at {path} has non-mapping 'types' section")

    entries = _build_entries(types_payload)
    return AzureResourceTypeRegistry(metadata=metadata, entries=entries)


@lru_cache(maxsize=1)
def load_registry() -> AzureResourceTypeRegistry:
    """Load and cache the registry from the default location."""
    return load_registry_from_path(_DEFAULT_REGISTRY_PATH)


def find_entry(name: str) -> Optional[AzureResourceTypeEntry]:
    """Convenience wrapper around the cached registry's ``find()``."""
    return load_registry().find(name)


def reset_cache() -> None:
    """Clear the cached registry. Intended for tests."""
    load_registry.cache_clear()
