apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "argocd-app"
        matchMode: "substring"
      group: "{{resource.resource.metadata.namespace}}"
    - match:
        type: pattern
        matchType: base-name
        pattern: "argocd-helm"
        matchMode: "substring"
      group: "{{resource.resource.metadata.namespace}}"