apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "aws-c7n-rds-health"
        matchMode: exact
      group: "AWS Region {{region}} (Account {{account_id}})"