apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "az-lb-health"
        matchMode: substring
        properties: [name]
      group: "{{resource_group.name}}"
    - match:
        type: pattern
        matchType: base-name
        pattern: "az-appgw-health"
        matchMode: substring
        properties: [name]
      group: "{{resource_group.name}}"
    - match:
        type: pattern
        matchType: base-name
        pattern: "az-appsvc-triage"
        matchMode: substring
        properties: [name]
      group: "{{resource_group.name}}"
    - match:
        type: pattern
        matchType: base-name
        pattern: "az-vm-triage"
        matchMode: substring
        properties: [name]
      group: "{{resource_group.name}}"
    - match:
        type: pattern
        matchType: base-name
        pattern: "az-aks-triage"
        matchMode: substring
        properties: [name]
      group: "{{resource_group.name}}"