apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "cert-health"
        matchMode: substring
      group: "{{resource.resource.metadata.namespace}}"
