apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "flux-kstmz"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "fluxcd-reconciliation"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"