apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "gcp-function-health"
        matchMode: exact
      group: "GCP Project {{project.name}} Resources"
    - match:
        type: pattern
        matchType: base-name
        pattern: "gcp-bucket-health"
        matchMode: exact
      group: "GCP Project {{project.name}} Resources"
    - match:
        type: pattern
        matchType: base-name
        pattern: "gke-cluster-health"
        matchMode: exact
      group: "GCP Project {{project.name}} Resources"