apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "http-ok"
        matchMode: exact
      group: "Public HTTP Endpoint Health"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ingress-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ingress-gce-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"