apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "ngx-ing-gmp"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ns-health"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "redis-health"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ss-health"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ds-health"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "depl-health"
        matchMode: substring
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "kong-ing-health"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "pvc-health"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "pod-resources"
        matchMode: substring
        properties: [name]
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "jenkins-health"
        matchMode: substring
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "image-check"
        matchMode: substring
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "sa-check"
        matchMode: substring
      group: "{{namespace.name}} ({{cluster.name}})"
