apiVersion: runwhen.com/v1
kind: MapCustomizationRules
spec:
  groupRules:
    - match:
        type: pattern
        matchType: base-name
        pattern: "ngx-ing-gmp"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ns-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "redis-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ss-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ds-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "depl-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "kong-ing-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "pvc-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "pod-resources"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "jenkins-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "image-check"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "sa-check"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "loki-hlthck"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "gitops-gh-fix"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "gitops-gh-fix"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "jaeger-http"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "postgres-operations"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "postgres-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "depl-ops"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "depl-logs-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "ss-logs-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "k8s-otelcollector"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "k8s-istio-system-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"
    - match:
        type: pattern
        matchType: base-name
        pattern: "stacktrace-health"
        matchMode: exact
      group: "{{namespace.name}} ({{cluster.name}})"