version: '0.5'
lastBuildDate: '2023-07-14T05:00:00'
lastUploadDate: '2023-07-14T06:00:00'
slxs:
- fullName: full-test-cluster-cpu
  name: test-cluster-cpu
- fullName: full-test-cluster-disk
  name: test-cluster-disk
- fullName: full-test-cluster-mem
  name: test-cluster-mem
