# Build the RunWhen Local image
name: Discovery Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/test.yaml"

permissions:
  contents: "read"
  id-token: "write"
  security-events: "write"
  actions: "read"

env:
  PROJECT_ID: runwhen-nonprod-shared
  DEFAULT_BRANCH: "origin/${{ github.event.repository.default_branch }}"
  KUBECONFIG: ${{secrets.SANDBOX_KUBECONFIG}}


jobs:
  k8s-basic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - uses: actions/checkout@v2
        name: Checkout

      - name: Build Image
        run: |-
          cd .test/k8s/basic
          echo "${{ env.KUBECONFIG }}" > kubeconfig.secret
          docker buildx create --use --name=mybuilder
          docker buildx inspect --bootstrap
          task build-rwl

      - name: Run k8s/basic ci-test-1
        run: |-
          cd .test/k8s/basic
          echo "${{ env.KUBECONFIG }}" > kubeconfig.secret
          task ci-test-1
          task clean


      - name: Run k8s/basic ci-test-2
        run: |-
          cd .test/k8s/basic
          echo "${{ env.KUBECONFIG }}" > kubeconfig.secret
          task ci-test-2
          task clean
          